In [11]:
import pandas as pd
import numpy as np

In [2]:
dib = pd.read_csv('Diabetes Example Data.csv')

In [3]:
dib.head()

   Blood Sugar Level Diabetes
0                190       No
1                240      Yes
2                300      Yes
3                160       No
4                200      Yes

In [4]:
# Converting Yes to 1 and No to 0
dib['Diabetes'] = dib['Diabetes'].map({'Yes': 1, 'No': 0})

In [5]:
dib.head()

   Blood Sugar Level  Diabetes
0                190         0
1                240         1
2                300         1
3                160         0
4                200         1

In [6]:
# Putting feature variable to X
X = dib['Blood Sugar Level']

# Putting response variable to y
y = dib['Diabetes']

In [7]:
import statsmodels.api as sm

In [10]:
logm1 = sm.GLM(y,(sm.add_constant(X)), family = sm.families.Binomial())
logm1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                   10
Model:                            GLM   Df Residuals:                        8
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2.5838
Date:                Tue, 23 Jul 2019   Deviance:                       5.1676
Time:                        13:56:33   Pearson chi2:                     4.32
No. Iterations:                     7   Covariance Type:             nonrobust
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const               -13.5243      9.358     -1.445      0.148     -31.866       4.817
Blood Sugar Level     0.0637      0.044      1.439      0.150      -0.023       0.150
=====================================================================================
"""

In [12]:
churn_data = pd.read_csv("churn_data.csv")
internet_data = pd.read_csv("internet_data.csv")
customer_data = pd.read_csv("customer_data.csv")

In [30]:
#internet_data["OnlineBackup"].value_counts()

#internet_data["OnlineSecurity"].value_counts()
internet_data["InternetService"].value_counts()

Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

In [29]:
internet_data[internet_data.DeviceProtection =='No internet service']

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
11,7469-LKBCI,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
16,8191-XWSZG,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
21,1680-VDCWW,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
22,1066-JKSGK,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
33,7310-EGVHZ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
42,9867-JCZSP,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
58,3957-SQXML,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
68,3170-NMYVV,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
71,0731-EBJQB,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
73,8028-PNXHQ,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
79,3887-PBQAO,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
84,0318-ZOPWS,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
87,1862-QRWPE,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
88,2796-NNUFI,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
97,0278-YXOOG,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
98,3212-KXOCR,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
100,6380-ARCEH,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
101,3679-XASPY,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
109,2848-YXSMW,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
118,8402-OOOHJ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
121,2928-HLDBA,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
124,7219-TLZHO,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
127,6734-PSBAW,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
128,3930-ZGWVE,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
135,7799-LGRDP,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
137,3774-VBNXY,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
138,6217-KDYWC,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
144,1131-QQZEB,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
146,6837-BJYDQ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
154,3077-RSNTJ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
...,...,...,...,...,...,...,...,...,...
6830,7815-PDTHL,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6832,9173-IVZVP,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6840,1724-IQWNM,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6842,5546-QUERU,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6854,9700-ZCLOT,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6856,4534-WGCIR,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6867,5146-YYFRZ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6875,6848-HJTXY,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6880,6976-BWGLQ,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6887,2511-ALLCS,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6906,9945-PSVIP,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6911,0508-SQWPL,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6916,7242-EDTYC,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6920,2595-KIWPV,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6925,6508-NJYRO,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6929,0357-NVCRI,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6942,3454-JFUBC,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6944,9039-ZVJDC,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6951,9588-YRFHY,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6954,9364-YKUVW,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6958,3078-ZKNTS,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6969,4745-LSPLO,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
6994,0804-YGEQV,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7000,0052-YNYOT,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7005,9347-AERRL,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7017,4807-IZYOZ,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7019,9710-NJERN,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7020,9837-FWLCH,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7030,0871-OPBXW,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service
7037,2569-WGERO,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service

In [15]:
pd.set_option('display.max_columns', 500)
df = pd.merge(churn_data,internet_data,how="inner",on="customerID")
df = pd.merge(df,customer_data,how="inner",on="customerID")

df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,gender,SeniorCitizen,Partner,Dependents
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,No phone service,DSL,No,Yes,No,No,No,No,Female,0,Yes,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No,No,DSL,Yes,No,Yes,No,No,No,Male,0,No,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,No,DSL,Yes,Yes,No,No,No,No,Male,0,No,No
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,Male,0,No,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,No,Fiber optic,No,No,No,No,No,No,Female,0,No,No

In [16]:
ls_catfields =["PhoneService","PaperlessBilling","Churn","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport",
               "StreamingTV","StreamingMovies","Partner","Dependents"]

def binary_mapping(x):
    return x.map({"Yes":1,"No" :0})

df[ls_catfields] = df[ls_catfields].apply(binary_mapping)

In [17]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,gender,SeniorCitizen,Partner,Dependents
0,7590-VHVEG,1,0,Month-to-month,1,Electronic check,29.85,29.85,0,No phone service,DSL,0.0,1.0,0.0,0.0,0.0,0.0,Female,0,1,0
1,5575-GNVDE,34,1,One year,0,Mailed check,56.95,1889.5,0,No,DSL,1.0,0.0,1.0,0.0,0.0,0.0,Male,0,0,0
2,3668-QPYBK,2,1,Month-to-month,1,Mailed check,53.85,108.15,1,No,DSL,1.0,1.0,0.0,0.0,0.0,0.0,Male,0,0,0
3,7795-CFOCW,45,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,No phone service,DSL,1.0,0.0,1.0,1.0,0.0,0.0,Male,0,0,0
4,9237-HQITU,2,1,Month-to-month,1,Electronic check,70.70,151.65,1,No,Fiber optic,0.0,0.0,0.0,0.0,0.0,0.0,Female,0,0,0

In [19]:
# dummy variables

lsMulticlass =["Contract","PaymentMethod","MultipleLines","InternetService","gender"]

dummies = pd.get_dummies(df[lsMulticlass],drop_first =True)

df =pd.concat([df,dummies],axis =1)

df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,gender,SeniorCitizen,Partner,Dependents,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,gender_Male
0,7590-VHVEG,1,0,Month-to-month,1,Electronic check,29.85,29.85,0,No phone service,DSL,0.0,1.0,0.0,0.0,0.0,0.0,Female,0,1,0,0,0,0,1,0,1,0,0,0,0
1,5575-GNVDE,34,1,One year,0,Mailed check,56.95,1889.5,0,No,DSL,1.0,0.0,1.0,0.0,0.0,0.0,Male,0,0,0,1,0,0,0,1,0,0,0,0,1
2,3668-QPYBK,2,1,Month-to-month,1,Mailed check,53.85,108.15,1,No,DSL,1.0,1.0,0.0,0.0,0.0,0.0,Male,0,0,0,0,0,0,0,1,0,0,0,0,1
3,7795-CFOCW,45,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,No phone service,DSL,1.0,0.0,1.0,1.0,0.0,0.0,Male,0,0,0,1,0,0,0,0,1,0,0,0,1
4,9237-HQITU,2,1,Month-to-month,1,Electronic check,70.70,151.65,1,No,Fiber optic,0.0,0.0,0.0,0.0,0.0,0.0,Female,0,0,0,0,0,0,1,0,0,0,1,0,0

In [21]:
df["OnlineBackup"].astype('category').value_counts()

0.0    3088
1.0    2429
Name: OnlineBackup, dtype: int64

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("pima_indian_diabetes.csv")

In [4]:
data.head()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age,Diabetes
0,1,89,66,23,94,28.1,21,0
1,0,137,40,35,168,43.1,33,1
2,3,78,50,32,88,31.0,26,1
3,2,197,70,45,543,30.5,53,1
4,1,189,60,23,846,30.1,59,1

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
np.random.seed(100)
df_train, df_test = train_test_split(data, train_size = 0.70, test_size = 0.30
                                     , random_state = 100)

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
transform = MinMaxScaler()
df_x_values = df_train.drop("Diabetes",axis=1)

df_x_values[df_x_values.columns] =transform.fit_transform(df_x_values[df_x_values.columns])

df_x_values.head()

D:\DS\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age
169,0.529412,0.685714,0.60,0.509434,0.187726,0.327198,0.285714
265,0.352941,0.521429,0.75,0.000000,0.374248,0.028630,0.928571
386,0.058824,0.464286,0.60,0.603774,0.070999,0.425358,0.166667
241,0.352941,0.700000,0.60,0.641509,0.150421,0.570552,0.142857
249,0.058824,0.592857,0.40,0.641509,0.559567,0.460123,0.000000

In [30]:
from numpy import median

for i in df_x_values.columns:
    print(i,round(median(df_x_values[i]),3))

No_Times_Pregnant 0.118
Plasma_Glucose 0.45
Diastolic_BP 0.512
Triceps 0.415
Insulin 0.134
BMI 0.309
Age 0.119

In [32]:
df_x_values.describe()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age
count,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000
mean,0.189352,0.474922,0.512226,0.415301,0.174849,0.308958,0.220195
std,0.187606,0.220506,0.154892,0.200289,0.147098,0.146812,0.235134
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.058824,0.307143,0.400000,0.250000,0.075812,0.212679,0.047619
50%,0.117647,0.450000,0.512500,0.415094,0.134176,0.308793,0.119048
75%,0.294118,0.621429,0.625000,0.566038,0.214801,0.391104,0.333333
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [41]:
import statsmodels 
import statsmodels.api as sm

X_train_lm = sm.add_constant(df_x_values)
#X_train_lm = df_x_values.copy()

y_train =df_train["Diabetes"].copy()

Model_1_LR = sm.GLM(y_train, X_train_lm).fit()

print(Model_1_LR.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                  274
Model:                            GLM   Df Residuals:                      266
Model Family:                Gaussian   Df Model:                            7
Link Function:               identity   Scale:                         0.15119
Method:                          IRLS   Log-Likelihood:                -125.90
Date:                Sun, 28 Jul 2019   Deviance:                       40.216
Time:                        15:53:56   Pearson chi2:                     40.2
No. Iterations:                     3   Covariance Type:             nonrobust
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -0.3692      0.095     -3.875      0.000      -0.556      -0.182
No_Times_Pregnant     0.2611      0.171      1.527      0.127      -0.074       0.596
Plasma_Glucose        0.9704      0.138      7.039      0.000       0.700       1.241
Diastolic_BP         -0.0443      0.171     -0.260      0.795      -0.378       0.290
Triceps               0.0978      0.156      0.625      0.532      -0.209       0.405
Insulin              -0.1245      0.201     -0.620      0.535      -0.518       0.269
BMI                   0.4644      0.222      2.089      0.037       0.029       0.900
Age                   0.2497      0.146      1.710      0.087      -0.037       0.536
=====================================================================================

In [42]:
from sklearn.feature_selection import RFE
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [53]:
y_train = y_train.copy()
X_train =df_x_values.copy()
## Defining Linear Model and performing Recurring Feaure eliminations method 

lm = LogisticRegression()
lm.fit(X_train,y_train)

_rfe = RFE(lm,5)
_rfe= _rfe.fit(X_train,y_train)

D:\DS\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DS\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DS\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DS\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [54]:

X_train.columns[_rfe.support_]

Index(['No_Times_Pregnant', 'Plasma_Glucose', 'Triceps', 'BMI', 'Age'], dtype='object')

In [50]:
y_train

169    1
265    0
386    0
241    0
249    0
178    1
362    0
19     1
26     0
297    0
35     0
157    0
39     0
244    0
375    1
10     1
199    0
184    1
208    0
367    1
65     0
259    0
285    0
41     0
378    0
203    0
104    1
128    0
216    1
151    0
      ..
4      1
100    0
211    1
245    1
141    1
364    0
155    1
86     1
93     1
137    0
58     0
316    1
363    1
228    1
143    0
390    0
240    0
290    0
14     1
226    0
66     0
53     1
354    1
350    0
79     0
343    0
359    0
323    0
280    1
8      1
Name: Diabetes, Length: 274, dtype: int64