In [151]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [467]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [468]:
movies = pd.read_csv(".\Movie+Assignment+Data.csv")
#movies

<font color="Blue"><b>Review Remaks</b></font>

<i> It is observed that total Data Set contain the 5,043 obseverations with the 28 properties<i>

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [469]:
# Write your code for inspection here
print("Move Shape: ", movies.shape)

movies.info()
movies.describe()

Move Shape:  (5043, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

<font color="Blue"><b>Review Remaks</b></font>

1. Major number of variables are in numarical formate and it makes easy to perform analysis<i>
2. Most of data is organized propely except some fields like gross and num_voted_uses like these fields may be required to normalized to for human readable formates
3. <b>title_year</b> is actually represent when this movie is released. in that case this can be converted to categorical variable insted of numarical variable

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [470]:
# Write your code for column-wise null count here
DS_null_col_wise =movies.isnull().sum() 
print(DS_null_col_wise.sort_values(ascending =False))

gross                        884
budget                       492
aspect_ratio                 329
content_rating               303
plot_keywords                153
title_year                   108
director_name                104
director_facebook_likes      104
num_critic_for_reviews        50
actor_3_name                  23
actor_3_facebook_likes        23
num_user_for_reviews          21
color                         19
duration                      15
facenumber_in_poster          13
actor_2_name                  13
actor_2_facebook_likes        13
language                      12
actor_1_name                   7
actor_1_facebook_likes         7
country                        5
movie_facebook_likes           0
genres                         0
movie_title                    0
num_voted_users                0
movie_imdb_link                0
imdb_score                     0
cast_total_facebook_likes      0
dtype: int64

<font color="Blue"><b>Review Remaks</b></font>

1. Majorly Gross and Budget variabls are having null values

In [471]:
# Write your code for row-wise null count here
DS_null_row_level = movies.isnull().sum(axis=1)
DS_null_row_level.sort_values(ascending =False)

279     15
4       14
4945    11
2241    11
2342    10
2143    10
2459     9
4948     8
4990     8
4946     8
4634     8
2828     8
962      8
2370     8
4460     8
4720     8
2870     8
4519     8
3419     7
3084     7
4372     7
1444     7
2552     7
4992     7
543      7
4517     7
2257     7
685      7
4767     7
2775     7
        ..
2703     0
2736     0
2719     0
2735     0
2734     0
2731     0
2730     0
2729     0
2728     0
2726     0
2725     0
2723     0
2722     0
2721     0
2720     0
2718     0
2704     0
2717     0
2716     0
2715     0
2714     0
2713     0
2712     0
2711     0
2709     0
2708     0
2707     0
2706     0
2705     0
0        0
Length: 5043, dtype: int64

<font color="Blue"><b>Review Remaks</b></font>

1. Not all rows having null values.

In [472]:
# Write your code for column-wise null percentages here
DS_null_columns_per =round((movies.isnull().sum() / len(movies.index))*100,2).sort_values(ascending = False)
print(DS_null_columns_per)

gross                        17.53
budget                        9.76
aspect_ratio                  6.52
content_rating                6.01
plot_keywords                 3.03
title_year                    2.14
director_name                 2.06
director_facebook_likes       2.06
num_critic_for_reviews        0.99
actor_3_name                  0.46
actor_3_facebook_likes        0.46
num_user_for_reviews          0.42
color                         0.38
duration                      0.30
facenumber_in_poster          0.26
actor_2_name                  0.26
actor_2_facebook_likes        0.26
language                      0.24
actor_1_name                  0.14
actor_1_facebook_likes        0.14
country                       0.10
movie_facebook_likes          0.00
genres                        0.00
movie_title                   0.00
num_voted_users               0.00
movie_imdb_link               0.00
imdb_score                    0.00
cast_total_facebook_likes     0.00
dtype: float64

<font color="Blue"><b>Review Remaks</b></font>

1. as per the above we can conculed that gross variable is null for more than 17% of observations. i.e 884 from 5k.

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [473]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies =movies.drop(["color","director_facebook_likes","actor_1_facebook_likes","actor_2_facebook_likes","actor_3_facebook_likes","actor_2_name",
             "cast_total_facebook_likes","actor_3_name","duration","facenumber_in_poster","content_rating","country","movie_imdb_link",
             "aspect_ratio","plot_keywords"],axis =1)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

### Procedure

1. Generated list of columns with the % of nulls (after removing unwanted columns) and save in Variable <b> Review_null_columns </b>
2. filterd the columns having more than 5% of null values in variable <b> columns_having_high_nulls </b>
3. identified the list of all row indes having null values and save information "index_having_any_null"
4. executed drop command to drop rows

In [474]:
# Write your code for dropping the rows here
Review_null_columns = round((movies.isnull().sum() / movies.shape[0]) * 100,2)
columns_having_high_nulls =list(Review_null_columns[Review_null_columns > 5].index)

index_having_any_null=movies[movies[columns_having_high_nulls].isnull().sum(axis=1)>=1].index

movies=movies.drop(index_having_any_null,axis=0)

<font color="Blue"><b>Review Remaks</b></font>

1. after droping unncessessory rows columns having null values are less

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [475]:
# Write your code for dropping the rows here
movies =movies[movies.isnull().sum(axis=1)<=5]

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [476]:
# Write your code for filling the NaN values in the 'language' column here
movies.loc[movies.language.isna(),["language"]] ="English"

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [477]:
# Write your code for checking number of retained rows here
movies.shape

(3891, 13)

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [478]:
# Write your code for unit conversion here
movies.budget = movies.budget/1000000
movies.gross = movies.gross/1000000

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [479]:
# Write your code for creating the profit column here
movies["profit"] = movies.gross - movies.budget

In [480]:
# Write your code for sorting the dataframe here
movies=movies.sort_values(by="profit",ascending =False)

In [481]:
top10 = movies[:10]
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [482]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(subset = None, keep = 'first', inplace = True)

In [483]:
# Write code for repeating subtask 2 here
top10 = movies[:10]
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [484]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250=movies[movies.num_voted_users>25000].sort_values(by ="imdb_score",ascending=False)

IMDb_Top_250["Rank"] = pd.Series(IMDb_Top_250['imdb_score'].rank(ascending=False), dtype=int)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.0,1994.0,9.3,108000,3.341469,1
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.0,1972.0,9.2,43000,128.821952,2
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.0,1974.0,9.0,14000,44.300000,3
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061,3
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.0,2003.0,8.9,16000,283.019252,6
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.0,1993.0,8.9,41000,74.067179,6
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.2,1966.0,8.9,20000,4.900000,6
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.0,1994.0,8.9,45000,99.930000,6
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,11
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,11
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.0,1980.0,8.8,17000,272.158751,11
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.0,1994.0,8.8,59000,274.691196,11
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.0,2001.0,8.8,21000,220.837577,11
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.4,1975.0,8.7,32000,107.600000,17
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.3,2002.0,8.7,28000,4.263397,17
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665,17
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.0,1954.0,8.7,11000,-1.730939,17
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.0,2002.0,8.7,10000,246.478898,17
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.0,1990.0,8.7,25000,21.836394,17
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.0,1999.0,8.7,25000,108.383253,17
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.0,1991.0,8.6,40000,111.727000,24
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.5,1936.0,8.6,0,-1.336755,24
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.5,1998.0,8.6,35000,-0.787759,24
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.0,1998.0,8.6,22000,146.119491,24
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.0,1995.0,8.6,28000,17.272306,24
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.0,2001.0,8.6,28000,-8.950114,24
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.0,1995.0,8.6,39000,67.125340,24
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.0,2014.0,8.6,349000,22.991439,24
283,Ridley Scott,265.0,187.670866,Action|Drama|Romance,Djimon Hounsou,Gladiator,982637,2368.0,English,103.0,2000.0,8.5,21000,84.670866,37
1571,Francis Ford Coppola,261.0,78.800000,Drama|War,Harrison Ford,Apocalypse Now,450676,983.0,English,31.5,1979.0,8.5,19000,47.300000,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2220,Eric Valette,141.0,26.876529,Horror|Mystery,Johnny Lewis,One Missed Call,26624,189.0,English,27.0,2008.0,3.9,0,-0.123471,2580
2112,Fred Dekker,75.0,10.696210,Action|Crime|Sci-Fi|Thriller,CCH Pounder,RoboCop 3,35018,180.0,English,23.5,1993.0,3.9,716,-12.803790,2580
273,Bo Welch,109.0,100.446895,Adventure|Comedy|Family|Fantasy,Sean Hayes,The Cat in the Hat,36033,456.0,English,109.0,2003.0,3.8,946,-8.553105,2583
704,Marco Schnabel,150.0,32.178777,Comedy|Romance|Sport,Justin Timberlake,The Love Guru,43300,250.0,English,62.0,2008.0,3.8,0,-29.821223,2583
1447,Steven E. de Souza,63.0,33.423521,Action|Adventure|Comedy|Thriller,Ming-Na Wen,Street Fighter,53115,282.0,English,35.0,1994.0,3.8,0,-1.576479,2583
808,Uwe Boll,140.0,4.535117,Action|Adventure|Fantasy|Thriller,Jason Statham,In the Name of the King: A Dungeon Siege Tale,38398,368.0,English,60.0,2007.0,3.8,0,-55.464883,2583
217,Joel Schumacher,183.0,107.285004,Action,Michael Gough,Batman & Robin,189855,1018.0,English,125.0,1997.0,3.7,0,-17.714996,2587
1660,John R. Leonetti,59.0,35.927406,Action|Adventure|Fantasy|Sci-Fi|Thriller,Brian Thompson,Mortal Kombat: Annihilation,36363,256.0,English,30.0,1997.0,3.7,1000,5.927406,2587
267,Jan de Bont,79.0,48.068396,Action|Crime|Romance|Thriller,Jason Patric,Speed 2: Cruise Control,60573,248.0,English,160.0,1997.0,3.7,894,-111.931604,2587
2518,Sidney J. Furie,94.0,15.681020,Action|Adventure|Family|Sci-Fi,Jim Broadbent,Superman IV: The Quest for Peace,33570,259.0,English,17.0,1987.0,3.6,1000,-1.318980,2589
2210,Malcolm D. Lee,153.0,32.014289,Comedy,Marisa Saks,Scary Movie 5,50337,177.0,English,20.0,2013.0,3.5,13000,12.014289,2590
2203,Jason Friedberg,122.0,36.658108,Comedy,Diedrich Bader,Vampires Suck,39095,187.0,English,20.0,2010.0,3.5,16000,16.658108,2590
1671,Troy Miller,85.0,26.096584,Comedy,Elden Henson,Dumb and Dumberer: When Harry Met Lloyd,30651,267.0,English,19.0,2003.0,3.4,1000,7.096584,2592
514,Dennis Dugan,156.0,74.158157,Comedy,Al Pacino,Jack and Jill,60370,264.0,English,79.0,2011.0,3.4,0,-4.841843,2592
4769,Tamra Davis,111.0,37.188667,Comedy|Drama,Britney Spears,Crossroads,34219,578.0,English,12.0,2002.0,3.3,0,25.188667,2595
1934,Bob Spiers,33.0,29.247405,Comedy|Family|Music,Jason Flemyng,Spice World,28377,261.0,English,25.0,1997.0,3.3,0,4.247405,2595
313,Pitof,212.0,40.198710,Action|Crime|Fantasy|Romance|Thriller,Frances Conroy,Catwoman,87451,660.0,English,100.0,2004.0,3.3,0,-59.801290,2595
1998,Uwe Boll,143.0,1.550000,Action|Adventure|Fantasy|Horror,Meat Loaf,BloodRayne,30628,471.0,English,25.0,2005.0,2.9,937,-23.450000,2597
2066,Joseph Sargent,80.0,20.763013,Adventure|Horror|Thriller,Judith Barsi,Jaws: The Revenge,30840,383.0,English,23.0,1987.0,2.8,0,-2.236987,2598
2182,Aaron Seltzer,99.0,48.546578,Comedy|Romance,Alyson Hannigan,Date Movie,50415,613.0,English,20.0,2006.0,2.7,806,28.546578,2600
1702,James Wong,130.0,9.353573,Action|Adventure|Fantasy|Sci-Fi|Thriller,Ian Whyte,Dragonball: Evolution,56451,524.0,English,45.0,2009.0,2.7,0,-35.646427,2600
1654,Jason Friedberg,111.0,38.232624,Comedy,Carmen Electra,Meet the Spartans,88518,409.0,English,30.0,2008.0,2.7,0,8.232624,2600
899,Martin Brest,131.0,5.660084,Comedy|Crime|Romance,Todd Giebenhain,Gigli,41620,418.0,English,54.0,2003.0,2.4,2000,-48.339916,2602
495,Roger Christian,174.0,21.471685,Action|Adventure|Sci-Fi,Richard Tyson,Battlefield Earth,65464,1308.0,English,44.0,2000.0,2.4,0,-22.528315,2602
2192,Jason Friedberg,112.0,39.737645,Adventure|Comedy,David Carradine,Epic Movie,89687,666.0,English,20.0,2007.0,2.3,0,19.737645,2604
2313,Uwe Boll,148.0,5.132655,Horror|Sci-Fi,Catherine Lough Haggquist,Alone in the Dark,37626,521.0,English,20.0,2005.0,2.3,1000,-14.867345,2604
319,Lawrence Guterman,78.0,17.010646,Comedy|Family|Fantasy,Jamie Kennedy,Son of the Mask,40751,239.0,English,84.0,2005.0,2.2,881,-66.989354,2606
2295,Bob Clark,32.0,9.109322,Comedy|Family|Sci-Fi,Scott Baio,Superbabies: Baby Geniuses 2,25371,129.0,English,20.0,2004.0,1.9,0,-10.890678,2607
2268,Jason Friedberg,111.0,14.174654,Comedy,Carmen Electra,Disaster Movie,74945,359.0,English,25.0,2008.0,1.9,0,-10.825346,2607
2834,Jon M. Chu,84.0,73.000942,Documentary|Music,Usher Raymond,Justin Bieber: Never Say Never,74351,233.0,English,13.0,2011.0,1.6,62000,60.000942,2609

In [485]:
Top_Foreign_Lang_Film = IMDb_Top_250[IMDb_Top_250.language !="English"]
Top_Foreign_Lang_Film[Top_Foreign_Lang_Film.movie_title.str.contains("Veer")]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.0,2004.0,7.9,2000,-4.078262,231

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [496]:
# Write your code for extracting the top 10 directors here
top10director=movies.groupby("director_name")["imdb_score"].mean().sort_values(ascending=False)[:10]
print(top10director)

#movies.pivot_table(values="imdb_score",index="director_name",aggfunc="mean").sort_values(by="imdb_score",ascending =False)[:10]

director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000
Name: imdb_score, dtype: float64

                       imdb_score
director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [498]:
# Write your code for extracting the first two genres of each movie here
movies["genre_1"] = movies.genres.apply(lambda x : x.split('|')[0])
movies["genre_2"] = movies.genres.apply(lambda x : x.split('|')[1] if len(x.split('|'))>=2 else x.split('|')[0] )

In [499]:
movies_by_segment = movies.groupby(["genre_1","genre_2"])

In [500]:
PopGenre = movies_by_segment["gross"].mean().sort_values(ascending = False)[:5]
PopGenre

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [440]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies[movies.actor_1_name.str.contains("Meryl Streep",na=False)]
Meryl_Streep.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama

In [441]:
Leo_Caprio = movies[movies.actor_1_name.str.contains("Leonardo DiCaprio",na=False)]
Leo_Caprio.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama

In [442]:
Brad_Pitt = movies[movies.actor_1_name.str.contains("Brad Pitt",na=False)]
Brad_Pitt.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller

In [443]:
# Write your code for combining the three dataframes here
Combined = pd.concat([Meryl_Streep,Leo_Caprio,Brad_Pitt],axis =0)

In [444]:
# Write your code for grouping the combined dataframe here
combined_actor_grp = Combined.groupby("actor_1_name")

In [447]:
# Write the code for finding the mean of critic reviews and audience reviews here
Top_review_compbined=combined_actor_grp["num_critic_for_reviews","num_user_for_reviews"].mean()

#combined avg reviewes num_critic_for_reviews + num_user_for_reviews
Top_review_compbined ["Total_avg_review"] = Top_review_compbined.num_critic_for_reviews + Top_review_compbined.num_user_for_reviews

#applying the sorting based on Total AVG Reviews from both
Top_review_compbined= Top_review_compbined.sort_values(by="Total_avg_review",ascending =False)

Top_review_compbined
#Combined.columns

,num_critic_for_reviews,num_user_for_reviews,Total_avg_review
actor_1_name,,,
Leonardo DiCaprio,330.190476,914.476190,1244.666667
Brad Pitt,245.000000,742.352941,987.352941
Meryl Streep,181.454545,297.181818,478.636364

**Checkpoint 6:** `Leonardo` has aced both the lists!