In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Reading the file
pima = pd.read_csv('pima_indian_diabetes.csv')

In [4]:
# Let's check the top 5 values
pima.head()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age,Diabetes
0,1,89,66,23,94,28.1,21,0
1,0,137,40,35,168,43.1,33,1
2,3,78,50,32,88,31.0,26,1
3,2,197,70,45,543,30.5,53,1
4,1,189,60,23,846,30.1,59,1

### Question-1: After normalising all the continuous features which feature has the maximum median value?

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# Putting feature variable to X
X = pima.drop(['Diabetes'],axis=1)

# Putting response variable to y
y = pima['Diabetes']

In [13]:
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7,test_size=0.3,random_state=100)

In [7]:
features = ['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps','Insulin', 'BMI', 'Age']

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()

In [14]:
X_train[features] = scaler.fit_transform(X_train[features])

In [15]:
X_train.describe()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age
count,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000
mean,0.189352,0.474922,0.512226,0.415301,0.174849,0.308958,0.220195
std,0.187606,0.220506,0.154892,0.200289,0.147098,0.146812,0.235134
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.058824,0.307143,0.400000,0.250000,0.075812,0.212679,0.047619
50%,0.117647,0.450000,0.512500,0.415094,0.134176,0.308793,0.119048
75%,0.294118,0.621429,0.625000,0.566038,0.214801,0.391104,0.333333
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

50% quantile corrosponds to median and Dialostic_BP seems to have maximum median value.

### Question-2: Build the model using all the variables. What is the p value for Triceps?

In [16]:
import statsmodels.api as sm

In [17]:
logm1 = sm.GLM(y_train,(sm.add_constant(X_train)), family = sm.families.Binomial())
logm1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                  274
Model:                            GLM   Df Residuals:                      266
Model Family:                Binomial   Df Model:                            7
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -122.11
Date:                Sun, 28 Jul 2019   Deviance:                       244.22
Time:                        16:04:36   Pearson chi2:                     264.
No. Iterations:                     5   Covariance Type:             nonrobust
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -5.1878      0.756     -6.864      0.000      -6.669      -3.706
No_Times_Pregnant     1.5575      1.124      1.386      0.166      -0.645       3.760
Plasma_Glucose        5.7310      0.980      5.851      0.000       3.811       7.651
Diastolic_BP         -0.4826      1.125     -0.429      0.668      -2.687       1.722
Triceps               0.6859      1.027      0.668      0.504      -1.326       2.698
Insulin              -0.8890      1.222     -0.728      0.467      -3.283       1.505
BMI                   3.1620      1.470      2.151      0.031       0.281       6.043
Age                   1.5469      0.953      1.624      0.104      -0.321       3.414
=====================================================================================
"""

### Question-3: Use RFE and choose 5 features, which two features are not selected by RFE?

In [18]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
from sklearn.feature_selection import RFE
rfe = RFE(logreg, 5)             # running RFE with 13 variables as output
rfe = rfe.fit(X,y)
print(rfe.support_)           # Printing the boolean results
print(rfe.ranking_)

[ True  True  True  True False  True False]
[1 1 1 1 3 1 2]

In [19]:
X.columns[rfe.support_]

Index(['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps',
       'BMI'],
      dtype='object')

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy_score(y_true, y_pred)
#metrics.precision_score(y_true, y_pred)
#metrics.recall_score(y_true, y_pred)
#metrics.f1_score(y_true, y_pred)

NameError: name 'y_true' is not defined

In [27]:
from sklearn import datasets, linear_model, metrics

In [29]:
lm = LogisticRegression()

fit=lm.fit(X_train,y_train)

In [35]:
#X_test

fit.predict(pd.DataFrame(scaler.transform(X_test)))

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [37]:
actual_data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/PZ2x3L59Q1k7jbRv02BJJjjZY/sample_diabetes_actual.csv")
actual_data.head()

   Diabetes   id
0         0   82
1         0  300
2         0   37
3         1  338
4         0  182

In [ ]:
import numpy as np
import pandas as pd
import json
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, linear_model, metrics

from sklearn import datasets, linear_model, metrics

# read training data
diabetes_train = pd.read_csv("/data/training/diabetes_train.csv")

# read test data
diabetes_test = pd.read_csv("/data/test/diabetes_test.csv")

# read the file containing actual labels (for computing scores)
actual_data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/PZ2x3L59Q1k7jbRv02BJJjjZY/sample_diabetes_actual.csv")


print(diabetes_train.head())
print(diabetes_test.head())
print(actual_data.head())


## WRITE YOUR CODE HERE ##

# create logistic regression object
log_model = LogisticRegression()

#  create x_train and y_train
x_train = diabetes_train.iloc[:, :7]
y_train = diabetes_train.iloc[:, 7]
y_true = actual_data.iloc[:, 0]


# Fit the model
log_model.fit(x_train,y_train)

 

# make predictions
y_pred = log_model.predict(diabetes_test.iloc[:, :7])

 

accuracy_score = round(metrics.accuracy_score(y_true, y_pred),2)
precision_score = round(metrics.precision_score(y_true, y_pred),2)
recall_score = round(metrics.recall_score(y_true, y_pred),2)
f1_score = round(metrics.f1_score(y_true, y_pred),2)

 

print(accuracy_score, precision_score, recall_score, f1_score)


# write the scores into the output file as a dictionary
# this code is already written for you
d = {'recall_score': recall_score,
    'f1_score': f1_score,
    'accuracy_score': accuracy_score,
    'precision_score': precision_score}
print(d)

# writing the dictionary to output file
# code is already written
with open('/code/output/answers.txt', 'w') as file:
     file.write(json.dumps(d))

flag
0  upvotes  -  1  comments
thumb_upUpvote


pd.set_option('display.max_columns', 500)

In [43]:
n=int(153)

strv = str(n)
s =0

for i in strv:
    s= s+ int(i) ** len(strv)

if (n == s ):
    print(True)
else:
    print(False)

True

In [42]:
for i in strv:
        s= s+ int(i) ** len(strv)

1
5
3

In [44]:
series1=pd.Series([1,2,3,4,5,6,7])
series2=pd.Series([1,3,7])

In [50]:
series1[series1.isin(series2)].index

Int64Index([0, 2, 6], dtype='int64')

In [51]:
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/8NMooe4G0ENEe8z9q5ZvaZA7/googleplaystore.csv")
#add your cleaning code here

In [73]:
df.Installs=df.Installs.str.replace(',','')
df.Installs=df.Installs.str.replace('+','')

In [66]:
df=df[df.Installs !="Free"]

In [78]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/8NMooe4G0ENEe8z9q5ZvaZA7/googleplaystore.csv")
#add your cleaning code here
df.Installs=df.Installs.str.replace(',','')
df.Installs=df.Installs.str.replace('+','')
df=df[df.Installs !="Free"]
df["Installs"] = df.Installs.astype(int)
print(df.corr())

            Rating  Installs
Rating    1.000000  0.051355
Installs  0.051355  1.000000

In [90]:
wholesale = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/OkbnaOBqrBXZOpRQw1JGMgaM9/Wholesale_Data.csv')

# Write your code here. Make sure that you change the values in the column 'Channel' inplace. 

mydic = {"H":"Hotel"
         ,"Hotel":"Hotel"
         ,"Hot":"Hotel"
         ,"Cafe":"Cafe"
         ,"Caffe":"Cafe"
         ,"C":"Cafe"
         ,"R":"Restaurant"
         ,"Restaurant":"Restaurant"
         ,"Rest":"Restaurant"}

#wholesale.Channel.apply(lambda x:map(x))

wholesale.Channel=["Hotel" if x == "H" else x for x in  wholesale.Channel]
wholesale.Channel=["Hotel" if x == "Hot" else x for x in  wholesale.Channel]
wholesale.Channel=["Cafe" if x == "Caffe" else x for x in  wholesale.Channel]
wholesale.Channel=["Cafe" if x == "C" else x for x in  wholesale.Channel]
wholesale.Channel=["Cafe" if x == "C" else x for x in  wholesale.Channel]
wholesale.Channel=["Restaurant" if x == "R" else x for x in  wholesale.Channel]
wholesale.Channel=["Restaurant" if x == "Rest" else x for x in  wholesale.Channel]

wholesale.Channel.value_counts()

Cafe          123
Hotel         111
Restaurant    101
Hote           35
Name: Channel, dtype: int64

In [91]:
import pandas as pd
wholesale = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/OqwpypRKN09x5GYej2LvVrprn/Wholesale_Data_Cleaned.csv')

In [98]:
wholesale["Tot"]=wholesale.iloc[:,:6].sum(axis=1)

wholesale.groupby("Channel")["Tot"].sum().sort_values(ascending =False).index[0]

'Hotel'